# Generated by Django 5.0.9 on 2024-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('personalization', 'Personalization'), ('scent', 'Scent'), ('packaging', 'Packaging'), ('material', 'Material'), ('arrangement', 'Flower Arrangement')], max_length=100),
        ),
    ]
